version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "monorepo-github-actions-lambda-test-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wv1qvif09l3g"
s3_prefix = "monorepo-github-actions-lambda-test-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
